### ISSUE TITLE
minimizing built-in sentences

### ISSUE THREAD

**Issue by fireasembler** [Lartu/ldpl#127]
with the addition of the new sentence creation system, many of the built-in sentences are no longer needed to be built into the compiler. those sentences should instead be moved into the new standard library.

**Comment by Lartu** [comment]
Any statement in particular you are thinking of? :thinking:

**Comment by fireasembler** [comment]
`abs <num>` is an obvious one.
`floor` and `ceil`, and maybe optionally also `incr` and `decr`.
`join <text> and <text> in <var>` should be removed entirely imo.
do you want me to make a full list?

**Comment by Lartu** [comment]
No, it's okay, I get it. I wouldn't really remove the ones we have at the moment because that would break backwards compatibility with already written software that uses those statements and hasn't had imported the standard library. Even though probably there's no LDPL software out there I know for a fact that some companies are looking at us, not even kidding, so I wouldn't like to break backwards compatibility. Our docs promise it won't be broken, so it's a matter of principles.

But, from now on, we should evaluate whether a statement should be included into the language or added to the STDLib. For instance, `POWER` (to raise numbers to a power) or `SQRT` should maybe be added to the language in order to take advantage of the processor logarithm tables, as including them in a std briefcase would be very slow (and harder), but all the CSV commands I was talking about the other days should be part of the STDLib and not the language.

**Comment by fireasembler** [comment]
I'd really like to know more about those companies. Sounds interesting.

**Comment by Lartu** [comment]
> I'd really like to know more about those companies. Sounds interesting.

Sorry, I can't really say much at the moment, I hope you can understand :(

I came here to talk about minimizing built-in statements. I was thinking that once we have a true and tested "final" release of the language (before shifting our focus to the STD) we could maybe release LDPL 4.0, breaking a little bit backwards compatibility. We could remove redundant statements and tell people that have existing code in LDPL to update it to LDPL 4.0 by adding `IMPORT "lib/ldpl_base.ldpl"` or something like that (that would include the removed statements), thus making the language smaller. That would be nice.
