### ISSUE TITLE
Number subindexes not detected

### ISSUE THREAD

**Issue by Lartu** [Lartu/ldpl#164]
At the moment, the LDPL compiler doesn't find any errors in codes like

```
data:
myNum is number
otherNum is number

procedure:
store myNum:0 in otherNum
```

and thus the C++ compilation crashes after the IR is generated. This should be fixed :disappointed:

**Comment by Lartu** [comment]
@dgarroDC as you were working with sub-indexes and all that in the recent days (and thus you should remember how this all works better), is there any chance you could look into this issue?

**Comment by dgarroDC** [comment]
I can't debug this right now but after a quick look at the code, I think that [this](https://github.com/Lartu/ldpl/blob/10a2caaf5d411854630955fe62d0a8e61d5a54ec/src/ldpl.cpp#L1700) might be the problem, maybe we should also check that `indexes` if empty.

But anyway, can the `is_num_var` be simplified by just calling `variable_type` with the full token and verifying if the type is `NUMBER`? I mean, something like this:
```C++
bool is_num_var(string & token, compiler_state & state)
{
    return (variable_type(token, state) == vector<unsigned int>{1}):
}
```

This is related to the bug we discussed [here](https://github.com/Lartu/ldpl/issues/157#issuecomment-559887587) (`is_num_var` was returning true incorrectly), but when I fixed it (by replacing `token` with `var_name`), I removed that false positive but introduced this new false positive. In conclusion, it was okay to use `token`, the problem was all the other logic (dealing with indexes). We can remove all that logic and use `token` again, and the resulting function is much simpler.

This all also applies to the text case, of course.

**Comment by Lartu** [comment]
You are right, I do like the simpler function. We should take that approach.

**Comment by dgarroDC** [comment]
Fixed!

**Comment by Lartu** [comment]
Wonderful! Thank you very much!
